name: CI
on:
  pull_request:
    branches-ignore:
      - dependency-updates
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    CI:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            cache: "yarn"
            cache-dependency-path: "yarn.lock"
            node-version-file: ".nvmrc"
        - name: Convert Notebooks
          run: .build/scripts/convert_notebooks.sh
        - name: Build HTML
          run: yarn && yarn build
        - name: Deploy GitHub pages
          if: ${{ github.ref == 'refs/heads/main' }}
          run: yarn deploy